jobs:
  build_deploy:
    machine:
      image: ubuntu-latest
    steps:
      - checkout
      - run:
          name: "Install AWS CLI"
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awscli --upgrade
      - run: cd ../ && npm install &&  npm run start
