jobs:
  build_deploy:
    machine:
      image:ubuntu-latest
    steps:
      -checkout
      -run:
        name: Installing AWS CLI
        command:
          sudo apt-get update
          sudo apt-get install -y awscli